name: Scan Timings
### example integration for Hunted Labs Entercept in a pipeline

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'On-Demand Distributed Scan'  
        
env:
  REGISTRY: ghcr.io
     
jobs:


  ImageTest:
    runs-on: ubuntu-latest
    steps:
            
    - name: "Install Tools"
      run: |
        curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b ~/.local/bin
        curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b ~/.local/bin
        
    - name: "Log in to ghcr"
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}      

    - name: "Log in to dhi.io"
      uses: docker/login-action@v2
      with:
        registry: dhi.io
        username: ${{ github.actor }}
        password: ${{ secrets.DHI_TOKEN }}      

        
    - name: "Grype Pull and Scan"
      run: |
        grype -q alpine:latest
        sleep 1
        time -p grype -q dhi.io/alpine-base:3.23-alpine3.23-dev
        sleep 1
        time -p grype -q ghcr.io/pvnovarese/2026-01-demo:main
        sleep 1
        time -p grype -q dhi.io/python:3-debian13-dev
        sleep 1
        time -p grype -q dhi.io/postgres:18-alpine3.22-dev
        sleep 1
        ttime -p grype -q -p dhi.io/rust:1-debian13-dev
        sleep 1

    - name: "Grype SBOM Scan"
      run: |        
        syft -q -o syft-json=alpine.json dhi.io/alpine-base:3.23-alpine3.23-dev
        sleep 1
        time -p grype -q sbom:./alpine.json
        syft -q -o syft-json=demo.json ghcr.io/pvnovarese/2026-01-demo:main
        sleep 1
        time -p grype -q sbom:./demo.json
        syft -q -o syft-json=python.json dhi.io/python:3-debian13-dev
        sleep 1
        time -p grype -q sbom:./python.json
        syft -q -o syft-json=postgres.json dhi.io/postgres:18-alpine3.22-dev
        sleep 1
        time -p grype -q sbom:./postgres.json
        syft -q -o syft-json=rust.json dhi.io/rust:1-debian13-dev
        sleep 1
        time -p grype -q sbom:./rust.json
